/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-12-08 06:35:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.place;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.freeeat.place.model.vo.Place;
import com.freeeat.common.model.vo.PageInfo;
import com.freeeat.member.model.vo.Member;
import com.freeeat.place.model.vo.*;
import java.util.*;

public final class selectList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/place/../common/menubar_hj.jsp", Long.valueOf(1670479822675L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.freeeat.place.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.freeeat.member.model.vo.Member");
    _jspx_imports_classes.add("com.freeeat.common.model.vo.PageInfo");
    _jspx_imports_classes.add("com.freeeat.place.model.vo.Place");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Place> list = (ArrayList<Place>)request.getAttribute("list");	
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	String keyword = (String)request.getAttribute("keyword");
	
	int currentPage = pi.getCurrentPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	int maxPage = pi.getMaxPage();
	
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=dd7467174bce94b954b035b41a5bccf5&libraries=services\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("<title>'검색어'에 대한 검색 결과</title>\r\n");
      out.write("<style>\r\n");
      out.write("	.outer div{\r\n");
      out.write("		/* border: 1px solid red; */\r\n");
      out.write("		box-sizing: border-box;\r\n");
      out.write("	}\r\n");
      out.write("	.outer{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 2000px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("	.outer>div{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	/* header */\r\n");
      out.write("	#header{\r\n");
      out.write("		height: 200px;\r\n");
      out.write("	}\r\n");
      out.write("	#header > #resultText{\r\n");
      out.write("		font-size: 30px;\r\n");
      out.write("		font-weight: 700;\r\n");
      out.write("		height: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* content */\r\n");
      out.write("	#content{\r\n");
      out.write("		width:100%;\r\n");
      out.write("		height: 1700px;\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("	}\r\n");
      out.write("	/* content-filter */\r\n");
      out.write("	#selectfilter{\r\n");
      out.write("		width: 20%;\r\n");
      out.write("		float: left;\r\n");
      out.write("	}\r\n");
      out.write("	/* content-resultRest */\r\n");
      out.write("	#content .result{\r\n");
      out.write("		width: 50%;\r\n");
      out.write("		float: left;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	#resturantList > li{\r\n");
      out.write("		width: 30%;\r\n");
      out.write("		float: left;\r\n");
      out.write("		margin: 5px 5px;\r\n");
      out.write("	}\r\n");
      out.write("	#resturantTitle{\r\n");
      out.write("		font-size: 30px;\r\n");
      out.write("		font-weight: 700;\r\n");
      out.write("		padding-top: 30px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* content-map */\r\n");
      out.write("	#rightContent{\r\n");
      out.write("		height: 2000px;\r\n");
      out.write("		width: 30%;\r\n");
      out.write("		z-index: -1;\r\n");
      out.write("		float: left;\r\n");
      out.write("	}\r\n");
      out.write("	#map{\r\n");
      out.write("		height: 20%;\r\n");
      out.write("		margin : 20px;\r\n");
      out.write("		z-index: 1;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* content-resultContent */\r\n");
      out.write("	#contentsRecomm{\r\n");
      out.write("		float: left;\r\n");
      out.write("	}\r\n");
      out.write("	#contentsTitle{\r\n");
      out.write("		font-size: 30px;\r\n");
      out.write("		font-weight: 700;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* footer */\r\n");
      out.write("	#footer{\r\n");
      out.write("		height: 100px;\r\n");
      out.write("	}\r\n");
      out.write("	/* 페이징바 */\r\n");
      out.write("	.pagination{\r\n");
      out.write("  	padding: 30px 0;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.pagination ul{\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.pagination a{\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 10px 18px;\r\n");
      out.write("	color: #222;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.p1 a{\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	line-height: 40px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.p1 a.is-active{\r\n");
      out.write("	background-color: #88A201;\r\n");
      out.write("	border-radius: 100%;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

    String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("   \r\n");

 	ArrayList<Wish> wish = (ArrayList<Wish>)session.getAttribute("wish");
	Member loginMem = (Member)session.getAttribute("loginMem");
	// 로그인 전 : menubar.jsp가 로딩 될 때 null
	// 로그인 후 : menubar.jsp가 로딩 될 때 로그인한 회원의 정보가 담겨있음

	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <title>Freeeat</title>\r\n");
      out.write("  <link rel=\"icon\" href=\"/Freeeat/WebContent/resources/favicon.ico\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" />\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Hahmlet:wght@100&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("  @font-face {\r\n");
      out.write("     font-family: 'S-CoreDream-3Light';\r\n");
      out.write("     src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-3Light.woff') format('woff');\r\n");
      out.write("     font-weight: normal;\r\n");
      out.write("     font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("    /* common(공통) */\r\n");
      out.write("  body{\r\n");
      out.write("      color: #333;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      line-height: 1.4; /*줄 높이*/\r\n");
      out.write("      height: 3000px;\r\n");
      out.write("      font-family: 'S-CoreDream-3Light';\r\n");
      out.write("  }\r\n");
      out.write("  img{\r\n");
      out.write("      display: block;\r\n");
      out.write("  }\r\n");
      out.write("  a{\r\n");
      out.write("      text-decoration: none; \r\n");
      out.write("      color: #2c2a29;\r\n");
      out.write("  }\r\n");
      out.write("  .inner{\r\n");
      out.write("      width: 1100px;\r\n");
      out.write("      margin: 0 auto;/*가운데 정렬*/\r\n");
      out.write("      position: relative;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* Header */\r\n");
      out.write("  header{\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      background-color: #f6f5f0;\r\n");
      out.write("      border-bottom: 1px solid #c8c8c8;\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top:0;\r\n");
      out.write("      z-index: 20;\r\n");
      out.write("  }\r\n");
      out.write("  header> .inner{\r\n");
      out.write("      height: 120px;\r\n");
      out.write("  }\r\n");
      out.write("  header .logo{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      bottom: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      margin: auto;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  header .sub-menu{\r\n");
      out.write("      position:absolute;\r\n");
      out.write("      top: 10px;\r\n");
      out.write("      right: 0;\r\n");
      out.write("      display: flex;\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("  header .sub-menu ul.menu{\r\n");
      out.write("      display: flex; /*수평으로 정렬*/\r\n");
      out.write("  }\r\n");
      out.write("  header .sub-menu ul.menu li{\r\n");
      out.write("      position: relative;\r\n");
      out.write("  }\r\n");
      out.write("  header .sub-menu ul.menu li:before{/*구분선*/\r\n");
      out.write("      content: \"\";\r\n");
      out.write("      display: block;\r\n");
      out.write("      width: 1px;\r\n");
      out.write("      height: 12px;\r\n");
      out.write("      background-color: #e5e5e5;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      bottom: 0;\r\n");
      out.write("      margin: auto;\r\n");
      out.write("  }\r\n");
      out.write("  header .sub-menu ul.menu li:first-child:before{\r\n");
      out.write("      display: none;\r\n");
      out.write("  }\r\n");
      out.write("  header .sub-menu ul.menu a{\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      padding: 11px 16px;\r\n");
      out.write("      display: block;\r\n");
      out.write("      color: #656565;\r\n");
      out.write("  }\r\n");
      out.write("  header .sub-menu ul.menu a:hover{\r\n");
      out.write("      color: black;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  header .main-menu{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      bottom: 0;\r\n");
      out.write("      right: 0;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("      display: flex;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item .item__name{\r\n");
      out.write("      padding: 10px 20px 34px 20px;\r\n");
      out.write("      font-size: 17px;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item:hover .item__name{\r\n");
      out.write("      background-color: #2c2a29;\r\n");
      out.write("      color: #88A201 !important;\r\n");
      out.write("      border-radius: 6px 6px 0 0;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item:hover .item__name a{\r\n");
      out.write("      background-color: #2c2a29;\r\n");
      out.write("      color: #88A201 !important;\r\n");
      out.write("      border-radius: 6px 6px 0 0;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item .item__contents{\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      display: none;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item:hover .item__contents{\r\n");
      out.write("      display: block;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item .item__contents .contents__menu{\r\n");
      out.write("      background-color: #88A201;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item .item__contents .contents__menu>ul{\r\n");
      out.write("      display: flex ;\r\n");
      out.write("      padding: 20px 0;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item .item__contents .contents__menu>ul>li{\r\n");
      out.write("      width: 220px;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item .item__contents .contents__menu>ul>li h4{\r\n");
      out.write("      padding: 3px 0 12px 0;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item .item__contents .contents__menu>ul>li h4{\r\n");
      out.write("      padding: 3px 0 12px 0;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item .item__contents .contents__menu>ul>li ul li{\r\n");
      out.write("      padding: 5px 0;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      color: black;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("  }\r\n");
      out.write("  header .main-menu .item .item__contents .contents__menu>ul>li ul li a:hover{\r\n");
      out.write("      color:#fff ;\r\n");
      out.write("  }\r\n");
      out.write("  /* 최근본식당 시작 */\r\n");
      out.write("\r\n");
      out.write("  * {padding:0;margin:0;}\r\n");
      out.write("    input[id=\"menuicon\"] {display:none;}\r\n");
      out.write("    input[id=\"menuicon\"] + ul {\r\n");
      out.write("      display:block;\r\n");
      out.write("      position:fixed;\r\n");
      out.write("      right:0;\r\n");
      out.write("      top:20%;\r\n");
      out.write("      transform:translateY(-50%);\r\n");
      out.write("      transition:all .35s;\r\n");
      out.write("      text-align:right;\r\n");
      out.write("    }\r\n");
      out.write("    input[id=\"menuicon\"] + ul > li {\r\n");
      out.write("      display:block;\r\n");
      out.write("      width:100px;\r\n");
      out.write("      height:30px;\r\n");
      out.write("      position:relative;\r\n");
      out.write("      margin-top:-1px;}\r\n");
      out.write("    input[id=\"menuicon\"] + ul > li > a {\r\n");
      out.write("      display:block;\r\n");
      out.write("      width:auto;\r\n");
      out.write("      height:50px;\r\n");
      out.write("      overflow:hidden;\r\n");
      out.write("      transition:all .35s;}\r\n");
      out.write("    input[id=\"menuicon\"] + ul > li > label {\r\n");
      out.write("      display: block;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      width: auto;\r\n");
      out.write("      height: 30px;\r\n");
      out.write("      background: #dadada;\r\n");
      out.write("      margin: auto;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("    \r\n");
      out.write("    input[id=\"menuicon\"] + ul > li:nth-child(1) label span {\r\n");
      out.write("      display:block;\r\n");
      out.write("      position:absolute;\r\n");
      out.write("      width:50%;\r\n");
      out.write("      height:3px;\r\n");
      out.write("      border-radius:30px;\r\n");
      out.write("      background:#333;\r\n");
      out.write("      transition:all .35s;\r\n");
      out.write("      top:30%;\r\n");
      out.write("      left:50%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[id=\"menuicon\"]:checked + ul {\r\n");
      out.write("      z-index:2;\r\n");
      out.write("      right:300px;}\r\n");
      out.write("    input[id=\"menuicon\"]:checked + ul > li:nth-child(1) label {\r\n");
      out.write("      z-index:2;\r\n");
      out.write("      right:300px;}\r\n");
      out.write("    input[id=\"menuicon\"]:checked + ul > li:nth-child(1) label span:nth-child(1) {\r\n");
      out.write("      top:50%;\r\n");
      out.write("      left:50%;\r\n");
      out.write("      transform:translate(-50%,-50%) rotate(45deg);}\r\n");
      out.write("    div[class=\"sidebar\"] {\r\n");
      out.write("      width:300px;\r\n");
      out.write("      height:100%;\r\n");
      out.write("      background:#f5f5f5;\r\n");
      out.write("      position:fixed;\r\n");
      out.write("      top:0;\r\n");
      out.write("      right:-300px;\r\n");
      out.write("      z-index:1;\r\n");
      out.write("      transition:all .35s;}\r\n");
      out.write("    input[id=\"menuicon\"]:checked + ul + div {right:0;}\r\n");
      out.write("\r\n");
      out.write("    #recentList{\r\n");
      out.write("      padding: 10px 10px 10px 10px;\r\n");
      out.write("      display: flex;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #recentTitle{\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-size: 30px;\r\n");
      out.write("      margin: 10 10 10 10\r\n");
      out.write("    }\r\n");
      out.write("    #recentText{\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("    }\r\n");
      out.write("/* 최근 본 식당 끝 */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".main-menu .search{\r\n");
      out.write("      height: 34px;\r\n");
      out.write("      position: relative;\r\n");
      out.write("}\r\n");
      out.write(".main-menu .search input{\r\n");
      out.write("     width: 400px;\r\n");
      out.write("     height: 50px;\r\n");
      out.write("      padding: 4px 10px;\r\n");
      out.write("      border: 1px solid #ccc; \r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      outline: none;\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      color: black;\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("  }\r\n");
      out.write("  .main-menu .search input:focus{\r\n");
      out.write("      border-color:#C8E183 ;\r\n");
      out.write("  }\r\n");
      out.write("  .main-menu .search .material-icons{\r\n");
      out.write("      height: 30px;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 20px;\r\n");
      out.write("      bottom: 0;\r\n");
      out.write("      right: 10px;\r\n");
      out.write("      margin: auto;\r\n");
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("  }\r\n");
      out.write("  .main-menu .search .material-icons button{\r\n");
      out.write("	  border:none; \r\n");
      out.write("	  background-color:white;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .main-menu .search.focused .material-icons{\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!--HEADER-->\r\n");
      out.write("  <header>\r\n");
      out.write("    <div class=\"inner\">\r\n");
      out.write("      <!-- 로고(홈) -->\r\n");
      out.write("      <a href=\"");
      out.print(contextPath);
      out.write("/views/common/mainPage.jsp\" class=\"logo\"><!--/은 현재 index파일로 이동-->\r\n");
      out.write("        <img src=\"");
      out.print(contextPath);
      out.write("/resources/image/freeeatlogo.png\" alt=\"Freeeat\" style=\"height: 100%;\" >\r\n");
      out.write("      </a>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"sub-menu\">\r\n");
      out.write("        <ul class=\"menu\">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("          ");
 if(loginMem == null) { 
      out.write("\r\n");
      out.write("          <!-- 로그인 안했을 때 보이는 화면 -->\r\n");
      out.write("        \r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"");
      out.print( contextPath );
      out.write("/views/member/joinEnrollForm.jsp\">회원가입</a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"");
      out.print( contextPath );
      out.write("/views/member/loginEnrollForm.jsp\">로그인</a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("       ");
 } else {
      out.write("\r\n");
      out.write("            <!-- 로그인했을 때 보이는 화면 -->\r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"");
      out.print( contextPath );
      out.write("/views/member/MyPage.jsp\">마이페이지</a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("          <li>\r\n");
      out.write("           <a href='");
      out.print( contextPath );
      out.write("/logout.yj'>로그아웃</a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li>\r\n");
      out.write("            <a>");
      out.print( loginMem.getMemNickName() );
      out.write("님 건강한 하루 되세요😄</a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("		     \r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"");
      out.print(contextPath);
      out.write("/CSList.hj?cpage=1\">고객센터</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"main-menu\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <div class=\"search\">\r\n");
      out.write("            <form action=\"");
      out.print( contextPath );
      out.write("/selectList.hj\" method=\"get\">\r\n");
      out.write("              <input type=\"text\" name=\"keyword\" placeholder=\"식당명/지역명/유형명을 입력해주세용\">\r\n");
      out.write("              <input type=\"hidden\" name=\"cpage\" value=\"1\">\r\n");
      out.write("              <span class=\"material-icons\"><button type=\"submit\">search</button> </span>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\">카테고리</div>\r\n");
      out.write("          <div class=\"item__contents\">\r\n");
      out.write("            <div class=\"contents__menu\">\r\n");
      out.write("              <ul class=\"inner\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>지역별</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=서울\">서울</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=인천\">인천</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=경기\">경기</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=강원\">강원</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=충청\">충청</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=전라\">전라</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=경상\">경상</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=제주\">제주</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>유형별</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=비건\">비건</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=락토프리\">락토프리</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=슈가프리\">슈가프리</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=글루텐프리\">글루텐프리</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=동물복지\">동물복지</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4>업종별</h4>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=식당\">식당</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=1&keyword=카페\">카페/베이커리</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\"><a href=\"#\">콘텐츠</a></div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\" ><a href=\"#\" >피드</a></div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <div class=\"item__name\">ABOUT</div>\r\n");
      out.write("          <div class=\"item__contents\">\r\n");
      out.write("            <div class=\"contents__menu\">\r\n");
      out.write("              <ul class=\"inner\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4><a href=\"#\">Freeeat이란?</a></h4>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4><a href=\"#\">조직도</a></h4>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <h4><a href=\"#\">찾아오시는 길</a></h4>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--BADGES : 최근 본 식당-->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"badges\">\r\n");
      out.write("      <input type=\"checkbox\" id=\"menuicon\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li>\r\n");
      out.write("          <label for=\"menuicon\">\r\n");
      out.write("            최근 본 식당\r\n");
      out.write("          </label>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <div class=\"sidebar\">\r\n");
      out.write("        <h2 id=\"recentTitle\" style=\"\">최근 본 식당 (5) </h2>\r\n");
      out.write("        <hr>\r\n");
      out.write("        ");
for(int i = 0; i<3; i++){
      out.write("\r\n");
      out.write("          <div id=\"recentList\">\r\n");
      out.write("            <div id=\"recentText\">\r\n");
      out.write("                <h6>서울시 강남구</h6>\r\n");
      out.write("                <span>러빙헛 카페</span>\r\n");
      out.write("                <span>5.0</span>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"recentImg\">\r\n");
      out.write("              <img src=\"https://blog.kakaocdn.net/dn/Gcr9O/btqKrr0guJn/tGa7hxXpsuAgvZvgfSEw0k/img.jpg\" alt=\"\" width=\"150\" height=\"150\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div> <a href=\"#\">> 보러가기</a>&nbsp&nbsp<a href=\"#\">>삭제</a></div>\r\n");
      out.write("          <hr>\r\n");
      out.write("          ");
}
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  <br><br><br><br><br><br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"outer\">\r\n");
      out.write("		<div align=\"center\" id=\"header\">\r\n");
      out.write("			<br>\r\n");
      out.write("			\r\n");
      out.write("			<h2 id=\"resultText\">'");
      out.print(keyword );
      out.write("'에 대한 검색 결과</h2>\r\n");
      out.write("		\r\n");
      out.write("			<div align=\"right\" id=\"orderby\" >\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<button class=\"btn orderbyreview\" value=\"review\">후기순</button>\r\n");
      out.write("				<button class=\"btn orderbygrade\" value=\"grade\" >평점순</button>\r\n");
      out.write("				<button class=\"btn orderbywish\" value=\"wish\" >찜하기순</button>\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("				&nbsp &nbsps\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<script>\r\n");
      out.write("			</script>	\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("				<div id=\"selectfilter\" class=\"form-check\" >\r\n");
      out.write("					<h4>&nbsp필터</h4>\r\n");
      out.write("					<hr>\r\n");
      out.write("						<input type=\"checkbox\" id=\"all\"><label for=\"all\">&nbsp전체 선택</label><br>\r\n");
      out.write("						<input type=\"checkbox\" id=\"resturant\"><label for=\"resturant\">&nbsp식당</label><br>\r\n");
      out.write("						<input type=\"checkbox\" id=\"cafe\"><label for=\"cafe\">&nbsp카페/베이커리</label><br>\r\n");
      out.write("						<input type=\"checkbox\" id=\"vegan\"><label for=\"vegan\">&nbsp비건</label><br>\r\n");
      out.write("						<input type=\"checkbox\" id=\"racto\"><label for=\"racto\">&nbsp락토프리</label><br>\r\n");
      out.write("						<input type=\"checkbox\" id=\"sugar\"><label for=\"sugar\">&nbsp슈가프리</label><br>\r\n");
      out.write("						<input type=\"checkbox\" id=\"decaff\"><label for=\"decaff\">&nbsp디카페인</label><br>\r\n");
      out.write("						<input type=\"checkbox\" id=\"animal\"><label for=\"animal\">&nbsp동물복지</label><br>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"result\">\r\n");
      out.write("					<div class=\"title\">\r\n");
      out.write("						 <h3 align=\"center\" id=\"resturantTitle\">식당</h3>\r\n");
      out.write("						 <h3 align=\"right\">총 ");
      out.print(list.size() );
      out.write("건의 검색 결과&nbsp&nbsp</h3>\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					");
if(list.isEmpty()){ 
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						<h5>조회된 식당이 없습니다.</h5>\r\n");
      out.write("						\r\n");
      out.write("					");
} else { 
      out.write("\r\n");
      out.write("						");
for(Place p : list){ 
      out.write("\r\n");
      out.write("						<ul id=\"resturantList\">\r\n");
      out.write("						<!-- placeNo가져가기 -->\r\n");
      out.write("							<li>\r\n");
      out.write("								<div id=\"thumbnail\">\r\n");
      out.write("									<input type=\"hidden\" name=\"placeNo\" value=\"");
      out.print( p.getPlaceNo() );
      out.write("\"/>\r\n");
      out.write("									<img src=\"https://mp-seoul-image-production-s3.mangoplate.com/895299_1581556713673106.jpg?fit=around|600:*&crop=600:*;*,*&output-format=jpg&output-quality=80\" alt=\"\"\r\n");
      out.write("									width=\"100%\">\r\n");
      out.write("								\r\n");
      out.write("								</div>\r\n");
      out.write("									\r\n");
      out.write("								<div class=\"discription\">\r\n");
      out.write("									");

									String type =  p.getPlaceType();
									if(type.contains(",")){
									String[] typeArr = type.split(",");										
										for(int i=0; i<typeArr.length; i++){
										
      out.write("\r\n");
      out.write("										\r\n");
      out.write("										<span class=\"badge text-bg-success\">");
      out.print( typeArr[i] );
      out.write("</span>\r\n");
      out.write("										");
} 
      out.write("\r\n");
      out.write("									");
 }else{
      out.write("\r\n");
      out.write("									<span class=\"badge text-bg-success\">");
      out.print( type );
      out.write("</span>\r\n");
      out.write("									");
} 
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("									<div id=\"location\">");
      out.print(p.getPlaceAddress() );
      out.write("</div> \r\n");
      out.write("									<div id=\"name\">");
      out.print(p.getPlaceName() );
      out.write("</div>\r\n");
      out.write("									<div id=\"class\">");
      out.print( p.getGrade() );
      out.write("</div>\r\n");
      out.write("									<div id=\"count\">\r\n");
      out.write("										<span>\r\n");
      out.write("											<span class=\"material-symbols-outlined\">\r\n");
      out.write("												edit\r\n");
      out.write("											</span>\r\n");
      out.write("											");
      out.print(p.getReviewCount() );
      out.write("\r\n");
      out.write("										</span>\r\n");
      out.write("										<span>\r\n");
      out.write("											<span class=\"material-symbols-outlined\">\r\n");
      out.write("												favorite\r\n");
      out.write("											</span>\r\n");
      out.write("												");
      out.print(p.getWishCount() );
      out.write("\r\n");
      out.write("										</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("						");
}
      out.write("\r\n");
      out.write("					");
}
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("				</div>	\r\n");
      out.write("				\r\n");
      out.write("			<script>\r\n");
      out.write("				$(function(){\r\n");
      out.write("					// \r\n");
      out.write("					$(document).on('click', '#thumbnail', function(){\r\n");
      out.write("						var placeNo = $(this).children().eq(0).val();\r\n");
      out.write("						//console.log(placeNo);\r\n");
      out.write("						location.href = \"");
      out.print( contextPath );
      out.write("/placeDetail.mr?placeNo=\"+placeNo\r\n");
      out.write("					})\r\n");
      out.write("					\r\n");
      out.write("				});\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			</script>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			<!-- 지도 -->\r\n");
      out.write("			<div id=\"rightContent\">\r\n");
      out.write("				<p style=\"margin-top:-12px; margin: auto;\">\r\n");
      out.write("					<h3>식당 주소로 검색하기 </h3>\r\n");
      out.write("					<input type=\"text\" id=\"text1\" placeholder=\"지역명을 입력해주세요.\">\r\n");
      out.write("					<button id=\"btn1\">검색</button>\r\n");
      out.write("				</p>\r\n");
      out.write("				<div id=\"map\" style=\"width:500px;height:400px;\"></div>\r\n");
      out.write("				\r\n");
      out.write("				<script>\r\n");
      out.write("				var mapContainer = document.getElementById('map'), // 지도를 표시할 div \r\n");
      out.write("					mapOption = {\r\n");
      out.write("						center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표\r\n");
      out.write("						level: 3 // 지도의 확대 레벨\r\n");
      out.write("					};  \r\n");
      out.write("				\r\n");
      out.write("				// 지도를 생성합니다    \r\n");
      out.write("				var map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("				\r\n");
      out.write("				// 주소-좌표 변환 객체를 생성합니다\r\n");
      out.write("				$('#btn1').click(function(){\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				var geocoder = new kakao.maps.services.Geocoder();\r\n");
      out.write("					\r\n");
      out.write("				// 주소로 좌표를 검색합니다\r\n");
      out.write("				geocoder.addressSearch($('#text1').val(), function(result, status) {\r\n");
      out.write("				\r\n");
      out.write("					// 정상적으로 검색이 완료됐으면 \r\n");
      out.write("					 if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("				\r\n");
      out.write("						var coords = new kakao.maps.LatLng(result[0].y, result[0].x);\r\n");
      out.write("				\r\n");
      out.write("						// 결과값으로 받은 위치를 마커로 표시합니다\r\n");
      out.write("						var marker = new kakao.maps.Marker({\r\n");
      out.write("							map: map,\r\n");
      out.write("							position: coords\r\n");
      out.write("						});\r\n");
      out.write("				\r\n");
      out.write("						// 인포윈도우로 장소에 대한 설명을 표시합니다\r\n");
      out.write("						var infowindow = new kakao.maps.InfoWindow({\r\n");
      out.write("							content: '<div style=\"width:150px;text-align:center;padding:6px 0;\">검색지</div>'\r\n");
      out.write("						});\r\n");
      out.write("						infowindow.open(map, marker);\r\n");
      out.write("				\r\n");
      out.write("						// 지도의 중심을 결과값으로 받은 위치로 이동시킵니다\r\n");
      out.write("						map.setCenter(coords);\r\n");
      out.write("					} \r\n");
      out.write("				})\r\n");
      out.write("				\r\n");
      out.write("				});    \r\n");
      out.write("				</script>\r\n");
      out.write("				<!-- 지도 끝 -->\r\n");
      out.write("				<div id=\"contentsRecomm\">\r\n");
      out.write("					<h2 align=\"center\" id=\"contentsTitle\">추천 콘텐츠</h2>\r\n");
      out.write("					<ul id=\"contentsList\">\r\n");
      out.write("						");
 for (int i=0; i<3; i++){ 
      out.write("\r\n");
      out.write("							<li align=\"center\">\r\n");
      out.write("								<div align=\"center\" id=\"thumbnail_contents\">\r\n");
      out.write("									<img src=\"http://cdn.iconsumer.or.kr/news/photo/202205/24570_28706_3455.png\" alt=\"\"\r\n");
      out.write("									width=\"70%\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div id=\"discription_contents\">\r\n");
      out.write("									<span class=\"badge text-bg-success\">비건</span>\r\n");
      out.write("									<div id=\"contents_title\">따라하기 쉬운 비건메뉴 레시피</div> \r\n");
      out.write("									<p>한 줄정도 내용...</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("							");
}
      out.write("\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"#\"  style=\"margin: auto;\">> 더보기</a>\r\n");
      out.write("							</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("		<!-- .content end -->\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div id=\"footer\">\r\n");
      out.write("			<!-- 페이징바 -->\r\n");
      out.write("			<div class=\"pagination p1\">\r\n");
      out.write("				<ul>\r\n");
      out.write("				");
if(currentPage != 1){ 
      out.write("\r\n");
      out.write("				  <a href=\"");
      out.print( contextPath);
      out.write("/selectList.hj?cpage=");
      out.print(currentPage-1);
      out.write("\"><li><</li></a>\r\n");
      out.write("				 ");
} 
      out.write("\r\n");
      out.write("				 \r\n");
      out.write("				 ");
for(int i = startPage; i<=endPage; i++){ 
      out.write("	\r\n");
      out.write("				 		");
if(currentPage != i){ 
      out.write("\r\n");
      out.write("				  		<a href=\"");
      out.print(request.getContextPath() );
      out.write("/selectList.hj?cpage=");
      out.print( i );
      out.write("\"><li>");
      out.print( i );
      out.write("</li></a>\r\n");
      out.write("				  		");
}else{ 
      out.write("\r\n");
      out.write("				  		<a  class=\"is-active\" href=\"#\"><li>");
      out.print( i );
      out.write("</li></a>\r\n");
      out.write("						");
} 
      out.write("\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				");
if(maxPage != currentPage){ 
      out.write("\r\n");
      out.write("				  <a href=\"");
      out.print(contextPath);
      out.write("/selectList.hj?cpage=");
      out.print(currentPage+1);
      out.write("\"><li>></li></a>\r\n");
      out.write("				 ");
} 
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			  </div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	<!-- .outer end -->\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
