/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-12-12 00:50:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.report;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.freeeat.member.model.vo.*;

public final class reportInsertView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.freeeat.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	String contextPath = request.getContextPath();
	Member m = (Member)request.getAttribute("member");
	Member loginMem = (Member)session.getAttribute("loginMem");
	
	String msg = (String)request.getAttribute("msg");

      out.write("	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>리뷰작성하기</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	 @font-face {\r\n");
      out.write("		font-family: 'S-CoreDream-3Light';\r\n");
      out.write("		src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-3Light.woff') format('woff');\r\n");
      out.write("		font-weight: normal;\r\n");
      out.write("		font-style: normal;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	body {\r\n");
      out.write("		font-family: 'S-CoreDream-3Light';\r\n");
      out.write("		background-color: rgb(253, 219, 219);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	#reprot_outer{\r\n");
      out.write("		width:550px;\r\n");
      out.write("		height:840px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	#report_title{\r\n");
      out.write("		margin-top: 20px;\r\n");
      out.write("		text-align : center;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#report_title > h1{\r\n");
      out.write("		font-weight: 900;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#report-content-area{\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		width:500px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#report-content-area{\r\n");
      out.write("		margin-bottom : 15px;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#report-content-area .rca-left{\r\n");
      out.write("		flex-basis: 30%;\r\n");
      out.write("		width:50px;\r\n");
      out.write("		text-align:center;\r\n");
      out.write("		font-size:15px;\r\n");
      out.write("		padding-right: 10px;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	#report-content-area .rca-right{\r\n");
      out.write("		 flex-basis: 70%;\r\n");
      out.write("		 \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	#report-write{\r\n");
      out.write("	\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#report-write > textarea{\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#submit-area{\r\n");
      out.write("		text-align: center;	\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#select-report td{\r\n");
      out.write("		margin: auto;\r\n");
      out.write("		width:100%;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#report-wrap{\r\n");
      out.write("		width:500px;\r\n");
      out.write("		margin-top:20px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"report_outer\"> \r\n");
      out.write("		<div id=\"report-wrap\">\r\n");
      out.write("			<div id=\"report_top_area\">\r\n");
      out.write("				<div id=\"report_title\"><h1>신고하기</h1></div>\r\n");
      out.write("				\r\n");
      out.write("				");
 if(msg != null ){ 
      out.write("\r\n");
      out.write("					<div><h1>");
      out.print( msg  );
      out.write("</h1></div>\r\n");
      out.write("					<script>\r\n");
      out.write("						closeWin();\r\n");
      out.write("					</script>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				");
 if(m!=null){ 
      out.write("\r\n");
      out.write("				<table id=\"report-content-area\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th class=\"rca-left\">작성자</th>\r\n");
      out.write("						\r\n");
      out.write("						<td class=\"rca-right\">");
      out.print( m.getMemNickName() );
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th class=\"rca-left\">내용</th>\r\n");
      out.write("						<td class=\"rca-right\">");
      out.print( m.getMem_profile_savePath() );
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<br>\r\n");
      out.write("			\r\n");
      out.write("			");
 if (loginMem != null && m != null){ 
      out.write("\r\n");
      out.write("			<form action=\"");
      out.print( contextPath);
      out.write("/reportInsert.mr\" method=\"get\">\r\n");
      out.write("				<input type=\"hidden\" name=\"loginMemNo\" value=\"");
      out.print( loginMem.getMemNo() );
      out.write("\"/>\r\n");
      out.write("				<input type=\"hidden\" name=\"reviewNo\" value=\"");
      out.print( m.getReviewNo() );
      out.write("\"/>\r\n");
      out.write("				<div id=\"report-main-area\"></div>\r\n");
      out.write("					<h5> 사유 선택 </h5>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"select-report\">\r\n");
      out.write("\r\n");
      out.write("						<table>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									<label for=\"reason1\">\r\n");
      out.write("										<input id=\"reason1\" name=\"report-reason\" type=\"radio\" value=\"스팸홍보/도배글입니다.\" checked>스팸홍보/도배글입니다.\r\n");
      out.write("									</label>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									<label for=\"reason2\">\r\n");
      out.write("										<input id=\"reason2\" name=\"report-reason\" type=\"radio\" value=\"음란물입니다.\">음란물입니다.\r\n");
      out.write("									</label>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									<label for=\"reason3\">\r\n");
      out.write("										<input id=\"reason3\" name=\"report-reason\" type=\"radio\" value=\"불법정보를 포함하고 있습니다.\">불법정보를 포함하고 있습니다.\r\n");
      out.write("									</label>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									<label for=\"reason4\">\r\n");
      out.write("										<input id=\"reason4\" name=\"report-reason\" type=\"radio\" value=\"개인정보 노출 게시물입니다.\">개인정보 노출 게시물입니다.\r\n");
      out.write("									</label>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									<label for=\"reason5\">\r\n");
      out.write("										<input id=\"reason5\" name=\"report-reason\" type=\"radio\" value=\"욕설/생명경시/혐오/차별적 표현입니다.\">욕설/생명경시/혐오/차별적 표현입니다.\r\n");
      out.write("									</label>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									<label for=\"reason6\">\r\n");
      out.write("										<input id=\"reason6\" name=\"report-reason\" type=\"radio\" value=\"불쾌한 표현이 있습니다.\">불쾌한 표현이 있습니다.\r\n");
      out.write("									</label>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>\r\n");
      out.write("									<label for=\"reason7\">\r\n");
      out.write("										<input id=\"reason7\" name=\"report-reason\" type=\"radio\" value=\"기타\">기타\r\n");
      out.write("									</label>\r\n");
      out.write("									<div id=\"report-write\" >\r\n");
      out.write("										<textarea name=\"report-plus\" style=\"width:450px; height:200px; resize:none;\" placeholder=\"기타 선택시 필수 입력입니다.\" ></textarea>\r\n");
      out.write("									</div>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div id=\"submit-area\">				\r\n");
      out.write("					<input type=\"submit\" value=\"신고하기\" />\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		</div>\r\n");
      out.write("	 </div>\r\n");
      out.write("	 \r\n");
      out.write("	 <script>\r\n");
      out.write("		// 기타 눌렸을 때 텍스트박스 입력 안하면 안넘어 가게 \r\n");
      out.write("	 	$('#reason7').on('click', function(){\r\n");
      out.write("			if($('#reason7').prop('checked') == true){\r\n");
      out.write("				$('#report-write').children().attr('required', true);\r\n");
      out.write("			} else {\r\n");
      out.write("				$('#report-write').children().attr('required', false);\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("	 	})\r\n");
      out.write("	 	\r\n");
      out.write("	 	\r\n");
      out.write("	 	function closeWin(){\r\n");
      out.write("			window.close();\r\n");
      out.write("		}\r\n");
      out.write("	 	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	 </script>\r\n");
      out.write("	 \r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
