/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-11-23 07:08:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String contextPath = request.getContextPath();

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("      @font-face {\r\n");
      out.write("     font-family: 'S-CoreDream-3Light';\r\n");
      out.write("     src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-3Light.woff') format('woff');\r\n");
      out.write("     font-weight: normal;\r\n");
      out.write("     font-style: normal;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body{\r\n");
      out.write("        font-family: 'S-CoreDream-3Light';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color:black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul li{\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        line-height: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li a:hover{\r\n");
      out.write("        font-weight: 900;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    p{\r\n");
      out.write("        margin-top: 40px;\r\n");
      out.write("        margin-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #ft-list-area{\r\n");
      out.write("        margin-top: 28px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #footer-area{\r\n");
      out.write("        width:100%;\r\n");
      out.write("        /* background-color: blanchedalmond; */\r\n");
      out.write("        height:450px;\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    #footer-area-all, #footer-area-right, #footer-area-left{\r\n");
      out.write("        height: 450px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #footer-area-all{\r\n");
      out.write("        width:1100px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        background-color: aliceblue;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #footer-area-right{\r\n");
      out.write("        width:500px;\r\n");
      out.write("        background-color: rgba(161, 165, 156, 0.678);\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    #footer-area-left{\r\n");
      out.write("        width:600px;\r\n");
      out.write("        background-color: rgba(168, 178, 197, 0.603);\r\n");
      out.write("        float: left;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .click-box {\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        width:100px;\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        background-color: rgba(98, 154, 133, 0.668);\r\n");
      out.write("        color: white;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        border: 1px solid rgba(98, 154, 133, 0.668);\r\n");
      out.write("        border-radius: 30px;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .click-box:hover{\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        background-color:  rgba(138, 178, 164, 0.837);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    img{\r\n");
      out.write("        width:180px;\r\n");
      out.write("        height:180px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    #ft-btn-table{\r\n");
      out.write("        width:500px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"footer-area\">\r\n");
      out.write("        <div id=\"footer-area-all\">\r\n");
      out.write("            <div id=\"footer-area-left\">\r\n");
      out.write("                <!-- -->\r\n");
      out.write("                <div id=\"ft-list-area\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">회사소개</a></li> \r\n");
      out.write("                        <li><a href=\"#\">광고문의</a></li> \r\n");
      out.write("                        <li><a href=\"#\">인재채용</a></li> \r\n");
      out.write("                        <li><a href=\"#\">이용약관</a></li> \r\n");
      out.write("                        <li><a href=\"#\">개인정보처리방침</a></li> \r\n");
      out.write("                        <li><a href=\"#\">커뮤니티 가이드라인</a></li> \r\n");
      out.write("                        <li><a href=\"#\">이용안내</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("               <div>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        (주)FREEEAT친구들 <br>\r\n");
      out.write("                        서울특별시 남대문로120 대일빌딩 2층 C-Class <br>\r\n");
      out.write("                        대표이사:6명 <br>\r\n");
      out.write("                        사업자 등록번호 : 123-12-1234555 <a href=\"#\">[사업자정보확인]</a> <br>\r\n");
      out.write("                        고객센터:02-1234-1234 <br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        © 2022 Freeeat Co., Ltd. All rights reserved.\r\n");
      out.write("                    </p>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"footer-area-right\">\r\n");
      out.write("                <table id=\"ft-btn-table\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th colspan=\"2\">\r\n");
      out.write("                            <img src=\"");
      out.print( contextPath);
      out.write("/resources/image/freeeatlogo.png\" alt=\"\">\r\n");
      out.write("                        </th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"ft-table-area\"><button class=\"click-box\">FAQ</button></th>\r\n");
      out.write("                        <td> 궁금해할까봐 궁금증 적어놨음😉 </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"ft-table-area\"><button class=\"click-box\">문의</button></th>\r\n");
      out.write("                        <td> 뭐든지 물어봐삼~~😘 </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"ft-table-area\"><button class=\"click-box\">공지사항</button></th>\r\n");
      out.write("                        <td> FREEEAT한 공지공지사항사항 👀🌼 </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- <div id=\"footer-area-bottom\">\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                    (주)FREEEAT친구들 <br>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
